### ISSUE TITLE
File DP0007 will be deleted, question regarding image location

### ISSUE THREAD

**Issue by VictorSyntez** [trustoverip/deliverables#32]
File DP0007 will be deleted from the 'results' folder. 
Regarding image files. I understand that I stored them in both, therefore I need to delete them from one of them.  What will be better way of storing them: in the local 'image' folder inside DP0007 repo or in '_images' folder inside 'docs' folder?

_Originally posted by @VictorSyntez in https://github.com/trustoverip/deliverables/issues/31#issuecomment-757095556_

**Comment by vinomaster** [comment]
Images in _images are pertinent to the PORTAL itself.
Images associated to a specific recommendation (ie DP007) should be handled via local folder.
See: https://trustoverip.github.io/deliverables/process/contributing_basic_doc/#repo-organization-suggestions

**Comment by VictorSyntez** [comment]
I will create PR to remove DP0007 image files from '_images' folder
