### ISSUE TITLE
[PORTAL] Add TSS001 Governance Stack to proposed deliverables

### ISSUE THREAD

**Issue by kkkulkarni** [trustoverip/deliverables#44]

**Comment by vinomaster** [comment]
The Deliverables Portal needs to be updated:
* [here proposed](https://trustoverip.github.io/deliverables/results/proposed/) AND
* [here - POR](https://trustoverip.github.io/deliverables/results/2021Q1/)

**Comment by vinomaster** [comment]
Fixed by @sankarshanmukhopadhyay in the above referenced PRs.
