### ISSUE TITLE
[DP0031] Principles of SSI Task Force deliverables

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [trustoverip/deliverables#46]
Setting up the PR for the deliverables of the Principles of SSI Task Force

The files are available from the PR https://github.com/trustoverip/deliverables/pull/45

**Comment by vinomaster** [comment]
PR #45 has added the content.  Before closing this issue as complete, we need to has a PR on the updates to:

- [Q2 Priorities](https://trustoverip.github.io/deliverables/results/2021Q2/)
- [Proposed Deliverables - Recommendations](https://trustoverip.github.io/deliverables/results/proposed/#recommendations)

On the [second item](https://trustoverip.github.io/deliverables/results/proposed/#recommendations) there was a miscommunication on ID and title. Just **replace the last row** with your desired text and info.

**Comment by sankarshanmukhopadhyay** [comment]
The required additional PRs are now set up.
